### ISSUE TITLE
pm2 file is not working in 1.0.0

### ISSUE THREAD

**Issue by jokaorgua** [ptnotifications/ptnotifications#1]
There is case sensitive error in pm2 file in 1.0.0 release. name of the jar should be PTNotifications.jar

**Comment by thoeve** [comment]
`{
  "apps": [
    {
      "name": "PT-Notifications",
      "cwd": ".",
      "script": "java",
      "args": [
        "-XX:+UseG1GC",
        "-XX:+UseStringDeduplication",
        "-XX:StringDeduplicationAgeThreshold=1",
        "-Xmx128m",
        "-jar",
        "PTNotifications.jar"
      ],
      "env": {
        "SPRING_PROFILES_ACTIVE": "prod"
      },
      "node_args": [],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "exec_interpreter": "",
      "exec_mode": "fork",
    "autorestart": false
    }
  ]
}
`

That should fix it.
