### ISSUE TITLE
[Enhacement] Add order to /pairs and /dca

### ISSUE THREAD

**Issue by jokaorgua** [ptnotifications/ptnotifications#12]
Would be great to have default ordering in /dca and /pairs commands by current profit percent. DESC or ASC nevermind.

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)

**Comment by jokaorgua** [comment]
in pairs ASC is not working

1 ProfitTrailer Monitor - Pairs: 
Currently 2 pairs in PAIRS

BCCETH - [ -0.77% ]  - 0.04932384 ETH
WTCETH - [ -0.17% ]  - 0.05005594 ETH

in DCA works ok

**Comment by thoeve** [comment]
Oops, forgot to add sorting on pairs. Will be fixed in next update. I hope you can live without it for now.

**Comment by jokaorgua** [comment]
sure, not a problem.

**Comment by thoeve** [comment]
This is fixed in release [1.0.2](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.2)
