### ISSUE TITLE
[Enhacement] Show number of pairs in  /pairs and /dca

### ISSUE THREAD

**Issue by MagicLazy** [ptnotifications/ptnotifications#13]

**Comment by MagicLazy** [comment]
Would be great to have the number of pairs in /dca and /pairs commands

**Comment by MagicLazy** [comment]
Sorry enhancement still open.

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
