### ISSUE TITLE
Lot of memory usage

### ISSUE THREAD

**Issue by jokaorgua** [ptnotifications/ptnotifications#15]
The notification should be small and tiny but i have
PT-Notifications │ 4  │ fork │ 20536 │ online │ 6       │ 2D     │ 0%  │ 660.5 MB

660mb of memory usage. I think this is not normal

**Comment by timh77** [comment]
Same here.

![afbeelding](https://user-images.githubusercontent.com/14058767/39291150-4cd7a468-4932-11e8-95bf-8ab0e1f3a73b.png)

**Comment by thoeve** [comment]
Are you guys running on Linux by any chance?

**Comment by jokaorgua** [comment]
yes. linux ubuntu 16.04 from my side (I would say 90% of PT users run linux)

**Comment by thoeve** [comment]
Could you give this a shot and share your results after a couple of hours?
[pm2-PTNotifications.json.zip](https://github.com/Roy4lz/ptnotifications/files/1950202/pm2-PTNotifications.json.zip)

**Comment by jokaorgua** [comment]
data right after the start
 status            │ online                                                    │
│ name              │ PT-Notifications                                          │
│ restarts          │ 0                                                         │
│ uptime            │ 64s                                                       │
│ script path       │ /usr/bin/java                                             │
│ script args       │ -XX:+UseConcMarkSweepGC -Xmx128M -jar PTNotifications.jar │
│ error log path    │ /home/joka/.pm2/logs/PT-Notifications-error-7.log         │
│ out log path      │ /home/joka/.pm2/logs/PT-Notifications-out-7.log           │
│ pid path          │ /home/joka/.pm2/pids/PT-Notifications-7.pid               │
│ interpreter       │ none                                                      │
│ interpreter args  │ N/A                                                       │
│ script id         │ 7                                                         │
│ exec cwd          │ /home/joka/pttnotifications                               │
│ exec mode         │ fork_mode                                                 │
│ node.js version   │ N/A                                                       │
│ watch & reload    │ ✘                                                         │
│ unstable restarts │ 0                                                         │
│ created at        │ 2018-04-26T07:50:10.518Z

PT-Notifications │ 7  │ fork │ 32249 │ online │ 0       │ 89s    │ 0%  │ 86.1 MB    │ joka

will wait couple of hours to update the post

**Comment by jokaorgua** [comment]
2 hours passed
PT-Notifications │ 7  │ fork │ 32249 │ online │ 0       │ 2h     │ 0%  │ 114.6 MB
will update in 8-9 hours once again

**Comment by jokaorgua** [comment]
worked for 15h
PT-Notifications │ 7  │ fork │ 30163 │ online │ 1       │ 15h    │ 0%  │ 127.8 MB

so at least better than that josn in zip file in releases

**Comment by timh77** [comment]
Server 1:  pt-notifications │ 2  │ fork │ 10673 │ online │ 4       │ 31h    │ 0%  │ **111.5 MB**
Server 2: pt-notifications │ 3  │ fork │ 32079 │ online │ 2       │ 29h    │ 0%   │ **137.0 MB**

Server 2 sends about double the messages compared to server 1.

**Comment by thoeve** [comment]
Good to see that we are no longer seeing ~500mb of usage.
