### ISSUE TITLE
Warn GetVersions - could not receive versions from GitHub

### ISSUE THREAD

**Issue by MagicLazy** [ptnotifications/ptnotifications#16]
I am getting this warning: "Warn GetVersions - could not receive versions from GitHub..."

**Comment by masonticehurst** [comment]
Also receiving this. Does not seem to affect notifications

**Comment by scottmsmith** [comment]
Same here

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
