### ISSUE TITLE
[Enhacement] Add avg price when bought from DCA

### ISSUE THREAD

**Issue by jokaorgua** [ptnotifications/ptnotifications#17]
Would be cool to have current avg price of the coin when the message from buy in DCA is sent

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)

**Comment by jokaorgua** [comment]
I think there is mistype in var in code

Instance: 1 ProfitTrailer Monitor
Quantity: 0.68000001
Rate: 0.0020462 BTC
Total: 0.0013942 (1) BTC
Avg cost: 0.00279888
Profit: -0.77%

Value of Avg cost here is Total cost or Current value. Should be avg cost around 0.002058001

**Comment by thoeve** [comment]
Maybe the wording is wrong but that's how average cost is described in the API. Perhaps Total cost would make more sense. Avg cost should be the avg price you paid per unit I guess.
