### ISSUE TITLE
[Enhacement] Add ability to switch off messages

### ISSUE THREAD

**Issue by jokaorgua** [ptnotifications/ptnotifications#18]
The soft has great feature of controlling bot through telegram. But as for me I have tons of messages from bot about buys and sells. Would be great to have ability to turn off sell messages or buy messages. Or both of them and leave only error messages and control

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
