### ISSUE TITLE
Could not get instance data for http://localhost:8060

### ISSUE THREAD

**Issue by cybermizrach** [ptnotifications/ptnotifications#2]
ProfitTrailer is running at port 8060. The license number and URL are correct as well. However, I've got the error below.

3|PT-Notif | 2018-04-22 01:27 +10:00: 2018-04-22 01:27:43 INFO Main - Starting...
3|PT-Notif | 2018-04-22 01:27 +10:00: 2018-04-22 01:27:44 ERROR Config - Could not get instance data for http://localhost:8060

**Comment by aycanurun** [comment]
2018-04-21 17:48:16 INFO Main - Starting...
2018-04-21 17:48:17 ERROR Config - Could not get instance data for http://localhost:8081

**Comment by sachah** [comment]
2018-04-21 15:53:33 INFO Main - Starting...
2018-04-21 15:53:33 ERROR Config - Could not get instance data for http://localhost:8081

C:\PT Notifications>pause
Press any key to continue . . .

**Comment by JHenneberg** [comment]
you have to put the correct settings in your PT2.0 application file
server.api_token = YOURSECRETAPIKEY (only numbers and letters) https://passwordsgenerator.net/
this token you also have to setup in your PT Notification file then restart PT2.0 and then PT-Notifications

**Comment by sachah** [comment]
I put server.api_token from PT 2 into notification and restarted but still not working. Any other suggestions?

**Comment by thoeve** [comment]
There is only 3 reasons that error pops up.

1. Your server.api_token does not match the instance_api_token set in PTN.
2. Your address is incorrect.
3. ProfitTrailer is not running.

**Comment by sachah** [comment]
Ok, but still not working. I copied API token directly from PT2 to Notifications. The localhost address is correct and Profit Trailer is running. Does API token need to be any special length? Localhost should just be http://localhost:8081? <http://localhost:8081/?> Not sure why it is not working since its very simple instructions to follow.

**Comment by aycanurun** [comment]
same problem were here then finaly i set "b1ttrexBTCbotapiToken" as api token and it worked.  now working with no problem with telegram. only saying discord token is invalid and not works with discord. token is correct actualy
