### ISSUE TITLE
i update this apps,i found this error

### ISSUE THREAD

**Issue by cnmars** [ptnotifications/ptnotifications#20]
6|PT-Notif | 2018-04-29 10:27 +08:00: 2018-04-29 10:27:12 INFO Main - Starting...

6|PT-Notif | 2018-04-29 10:27 +08:00: 2018-04-29 10:27:28 ERROR BotService - Incorrect telegram_channel_id

**Comment by thoeve** [comment]
Well your telegram channel id seems to be incorrect.
