### ISSUE TITLE
Blacklisting a coin removes other pairs from enabled_pairs

### ISSUE THREAD

**Issue by techhitnz** [ptnotifications/ptnotifications#22]
Blacklisting a coin alters the enabled_pairs value and removes everything except the first pair. I.e. If I have 10 pairs in the list it removes everything except the first pair

Ideally, this should read the list of enabled_pairs, and only delete the pair to be blacklisted.

**Comment by thoeve** [comment]
This is fixed in release [1.0.2](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.2)
