### ISSUE TITLE
[SQLITE_ERROR] SQL error or missing database (near "s": syntax error)

### ISSUE THREAD

**Issue by GvY85** [ptnotifications/ptnotifications#25]
I am getting (with a 2sec update rate) this message over and over in my console output:

[SQLITE_ERROR] SQL error or missing database (near "s": syntax error)

Bot seem to run fine except for the /last command that dows not show the last sells but some random sells

**Comment by GvY85** [comment]
Using PTN 1.0.1 and PT2.0.1
PT console shows no errors

**Comment by GvY85** [comment]
![dsc_0729](https://user-images.githubusercontent.com/38404393/39473101-760eb8c0-4d4d-11e8-8ce0-befdf6d01bd2.JPG)

**Comment by thoeve** [comment]
Delete your orders.db.

**Comment by GvY85** [comment]
Nope, that does not solve the problem

**Comment by thoeve** [comment]
Please visit the ProfitTrailer discord server for further support.
