### ISSUE TITLE
PTNotifications keeps spamming 'SOM triggered' message

### ISSUE THREAD

**Issue by GvY85** [ptnotifications/ptnotifications#27]
Hi, last night SOM got triggered and since them i got a message about it every second. So a couple thousand messages last night. I disabled PTN for now. Could this have to do with the SQL errors I also have in the console (see other issue posted)

**Comment by GvY85** [comment]
PTN console shows SQL error every second, PT console shows no errors at all. Using PTN 1.0.1 and PT2.0.1

**Comment by thoeve** [comment]
Delete your orders.db
