### ISSUE TITLE
/last command shows random (perhaps not even real) sells

### ISSUE THREAD

**Issue by GvY85** [ptnotifications/ptnotifications#28]
Hi, i noticed that /last does not show me the last sells PT made but some random coins and percentages. Could be real sells from the past but since they have very high percentages gain I think they are random data. 
Could this have to do with SOM spammin in bot and SQL errors I reported earlier?
PT console shows no errors btw

**Comment by GvY85** [comment]
Using PTN 1.0.1 and PT2.0.1

**Comment by MagicLazy** [comment]
Same problem for me.

**Comment by cupid-stunt** [comment]
I'm getting random data spewed to the phone now. 3k messages from 7 pairs over 9 hours! Had to turn it off! I'm not in SOM.

**Comment by thoeve** [comment]
This is fixed in release [1.0.2](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.2)
