### ISSUE TITLE
[Suggestion] Set specific adjustments in trades

### ISSUE THREAD

**Issue by eleuln** [ptnotifications/ptnotifications#29]
Hi!

I think it would be very useful to make specific adjustments in the pairs of trades (by Telgram, of course).
Ex: set specific sell_value to a pair.

**Comment by Aussiebjl** [comment]
SOM is enough,, it's a notification script not a PT Remote.

**Comment by thoeve** [comment]
Yes just like @Aussiebjl mentions this is a notications addon. Not meant for doing detailed PT controlling.
