### ISSUE TITLE
Can't disable settings

### ISSUE THREAD

**Issue by geeklingo** [ptnotifications/ptnotifications#3]
I want to use in a group TG ch and disabled the settings but they still work?

`#Enable or disable Sell Only Mode notifications
som_notifications = false
#Enable or disable Profit Trailer error notifications
error_notifications = false
#Enable or disable update notifications
update_notifications = false`

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
