### ISSUE TITLE
ERROR GetOrders - Invalid response from http://localhost:8081

### ISSUE THREAD

**Issue by UWillC** [ptnotifications/ptnotifications#30]
Cannot get rid of this... API keys are correct in application.properties and settings.properties, I had telegram bot configured in application.properties as well as in settings.properties, but still get these messages... any ideas ?

**Comment by cupid-stunt** [comment]
I had the same issue, when I changed localhost to the actual IP it cleared for me. Also check for whitespace around your keys if you pasted them in and make sure your random API key is the same as your bot.

**Comment by UWillC** [comment]
I checked both API keys and they are the same, I changed also localhost to the specific IP and the output was the same... but even if I am getting this ERROR I am receiving notifications on Telegram, but I am missing some.
Can it be the issue that I configured the same bot in ProfitTrailer application.properties and in settings.properties ?

**Comment by thoeve** [comment]
Make sure there is no empty space behind any of your tokens or addresses.

**Comment by UWillC** [comment]
Checked all these fields, still no changes... other suggestions?

**Comment by thoeve** [comment]
There are 4 main reasons for this error:
1. PT not running
2. Address wrong
3. server.api_token and instance_api_token not matching
4. Spaces behind any token or address.

If according to you this is all correct please join the ProfitTrailer Discord for further support.

**Comment by UWillC** [comment]
Will try then... thanks ??

**Comment by UWillC** [comment]
After update to 1.0.2 ERROR messages are not shownig, thanks.
