### ISSUE TITLE
Config could not be loaded

### ISSUE THREAD

**Issue by wrecker1977** [ptnotifications/ptnotifications#31]
im getting these error messages since i updated ptn.

-ConfigApi - Config could not be loaded from the rest api. Received message: 500
-Tradehistory - nl.komtek.pt.utils.i: Error in reading response Read timed out
-Application - Port 8081 is in use, close the program or try using using this port or try setting server.port (application.properties) to a different port.
-Error occured in TH. message null, result: null

Before i upgrade i didnt have any issues with ptn. I am getting buy and sold messages. Just these messages are constantly coming in my telegram.

Any idees?

Greetz

**Comment by thoeve** [comment]
Not related to PTN please contact support.
