### ISSUE TITLE
Just need a little help with a filter

### ISSUE THREAD

**Issue by ghost** [ptnotifications/ptnotifications#32]
How would I filter out the following messages? I don't see any specific guidance and I'm unsure if there can be any spaces. Are the filter values comma-delimited and space-allowed?

1 ProfitTrailer Monitor ERROR: ProfitTrailerService - Error occured in ticker, message Websocket error: Destroyed container cannot be restarted, result:

1 ProfitTrailer Monitor ERROR: ProfitTrailerService - CB - Error in reading response connect timed out

**Comment by thoeve** [comment]
You can use any word and it will filter any error containing that word.
