### ISSUE TITLE
[Feature Request] Allow usage of different channels or even bots per instance

### ISSUE THREAD

**Issue by Ronanza** [ptnotifications/ptnotifications#33]
Hi,

I'm using PT Notificati0ons with 4 PT instances and would like to use a different channel or even bot for each. This is possible with the standard notifications of PT (in application.properties), but afaik not with PT Notifcations. I can only specifiy one bot token and one channel ID.

discord_enabled = true
discord_bot_token_1 = abcdefg (bot for instance 1)
discord_bot_token_2 = uvwxyz (bot for instance 2)
discord_channel_id_1 = 12345 (channel for instance 1)
discord_channel_id_2 = 678910 (channel for instance 2)
etc.

Or am I missing something?
Thanks. This would be really cool.

**Comment by thoeve** [comment]
I've had this suggestion pass by a couple of times now so I'll definitly look into this. Thanks.

**Comment by thoeve** [comment]
Fixed in [1.1.0](https://github.com/Roy4lz/ptnotifications/releases/tag/1.1.0)
