### ISSUE TITLE
/blacklist works great, but then /whitelist doesn't enable it back

### ISSUE THREAD

**Issue by Concept211** [ptnotifications/ptnotifications#34]
I'd like to /blacklist a coin and then later remove that blacklisted coin. But it seems the only way to do that is to manually edit the PAIRS config by removing those line items.

I tried using the /whitelist option but it always gives me the following response:
_Could not find enabled_pairs or is set to ALL in pairs_

**Comment by thoeve** [comment]
This is fixed in release [1.0.2](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.2)
