### ISSUE TITLE
high memory consumption

### ISSUE THREAD

**Issue by avizmil** [ptnotifications/ptnotifications#37]
after running for few days, it got to 2.1 GB memory!
went down to 80MB  after restart

**Comment by thoeve** [comment]
How are you starting the app?

**Comment by avizmil** [comment]
pm2 according to the guides...not something special.
Checked now and it's on 282 MB

**Comment by thoeve** [comment]
Can you post me your pm2 file content?

**Comment by avizmil** [comment]
{
  "apps": [
    {
      "name": "PT-Notifications",
      "cwd": ".",
      "script": "java",
      "args": [
        "-XX:+UseG1GC",
        "-XX:+UseStringDeduplication",
        "-XX:StringDeduplicationAgeThreshold=1",
        "-Xmx128m",
        "-jar",
        "PTNotifications.jar"
      ],
      "env": {
        "SPRING_PROFILES_ACTIVE": "prod"
      },
      "node_args": [],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "exec_interpreter": "",
      "exec_mode": "fork",
    "autorestart": false
    }
  ]
}

**Comment by thoeve** [comment]
Use this

```
{
	"apps": [
		{
			"name": "PT-Notifications",
			"cwd": ".",
			"script": "java",
			"args": [
				"-XX:+UseConcMarkSweepGC",
				"-Xms64m",
				"-Xmx64m",
				"-jar",
				"PTNotifications.jar"
			],
			"node_args": [],
			"log_date_format": "YYYY-MM-DD HH:mm Z",
			"exec_interpreter": "",
			"exec_mode": "fork",
			"autorestart": false
		}
	]
}
````
That will solve your problem.

**Comment by avizmil** [comment]
will try it. Thanks
