### ISSUE TITLE
[Feature Request] Continue startup if PT is not available.

### ISSUE THREAD

**Issue by Ronanza** [ptnotifications/ptnotifications#38]
Hi, 

I‘m using a batch file to start all my bots, tracker and PT Notifications.
I‘ve included a timeout before starting PT Notifications as last step.
Due to various reasons the startup of individual bots can take longer than usual.
Since PTN aborts startup if one of my bot instances is not yet fully loaded, sometimes it doesn‘t load.

Please change startup sequence so that PTN does not abort startup in this case. PTN should load anyway and wait for PT to respond. Same as when I close a bot while PTN is already running.

Thanks,
Ronanza

**Comment by thoeve** [comment]
Fixed in [1.1.0](https://github.com/Roy4lz/ptnotifications/releases/tag/1.1.0)
