### ISSUE TITLE
ERROR Config - Could not get instance data for http://localhost:8081

### ISSUE THREAD

**Issue by viadata** [ptnotifications/ptnotifications#39]
Refer to this issue:
https://github.com/Roy4lz/ptnotifications/issues/2

Same problem. http://localhost:8081 is working correctly for ssh port forwarding to the local browser, and ProfitTrailer is running & trading. It's also accessible to pt tracker, which is working fine with the same host. server.api_token is the same for both, and multiple tokens have been tried.

**Comment by thoeve** [comment]
Please contact us on the PT discord for further support.
