### ISSUE TITLE
wrong notifications come

### ISSUE THREAD

**Issue by clippart** [ptnotifications/ptnotifications#4]
Simultaneously with the sale, a notification of the purchase comes, although the PT did not buy anything
![1](https://user-images.githubusercontent.com/33903011/39090230-6af22388-4603-11e8-9ef2-10649fc4b45f.PNG)

**Comment by MosselNL** [comment]
Same issue here:
![afbeelding](https://user-images.githubusercontent.com/8009578/39091134-3d9a5b22-45ee-11e8-96d8-db31b650d0e4.png)

It doesn't happen after every every sale.

**Comment by jokaorgua** [comment]
I have the same issue.

**Comment by smoochy** [comment]
Yap, happening to me also. It is not on every sale though

**Comment by thoeve** [comment]
This is indeed a bug and will be fixed inthe next upcoming release.

**Comment by weirders** [comment]
Appears it happens after I give the /all command. All is fine before that.

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
