### ISSUE TITLE
ISSUE: Stringindexoutofboundsexceptionstring_index_out_of_range10

### ISSUE THREAD

**Issue by cryptovictor1188** [ptnotifications/ptnotifications#41]
I have an interesting issue:

I am using the PtNotifications Addon and I have been receiving these kinds of message every 5 minutes (Reoccurring) : 

 **"ProfitTrailerService - openOders - java.lang.tringIndexOutOfBoundsException; String index out of range: -10"        

"ProfitTrailerService - Error occured in CB, message String Index out of range: -10, result:"     

"ProfitTrailer Service - Error occured in ticker, message No value was returned, result:"**

I found the issue on the Wiki but it was of no help:
Here is the wiki link: https://wiki.profittrailer.com/doku.php?id=common_errors#stringindexoutofboundsexceptionstring_index_out_of_range10

I reached out to multiple support members and tried our best to triage the issue....
We tried the following: 
- Reinstated new API Keys from Bittrex: 2 new keys (Defaults and Private). 
- Added my VPS (Vultr) IP Address to my Bittrex IP Whitelist (this did not help)
- http://localhost:8083/settings/test/reset (This seems to stop the issue but it does not resolve it as it will still happen if I restart the PtNotification system). 
- Many other trouble shooting with Settings etc. 
- Hard Reset of VPS
- Changed Ports

Please help me !

**Comment by thoeve** [comment]
These are PT errors being redirected to PTN to notify you of them. It has nothing to do with PTN it self. I would suggest looking for support in the PT Discord.
