### ISSUE TITLE
ERROR: com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by cryptovictor1188** [ptnotifications/ptnotifications#42]
Hello,

This is a second post of mine. There is another issue/Error with my Binance Bot PT Notification It reads at follows: 

@MyTPBot, [May 12, 2018 at 12:53:52 PM]:
ProfitTrailer notifications bot is now running...

2 Victors Bittrex Bot 1 ERROR: ProfitTrailerService - Error occured in chartData, message No value was returned, result:

2 Victors Bittrex Bot 1 ERROR: ProfitTrailerService - Error occured in ticker, message No value was returned, result:

@MyTPBot, [May 12, 2018 at 8:04:54 PM]:
1 Victors Binance Bot 1 ERROR: ProfitTrailerService - Handled exception com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $

1 Victors Binance Bot 1 ERROR: ProfitTrailerService - CB -
_____________________________________________________________________

Please let me know some insight on these issues. I have no idea what to do now or whom to ask for help except the developer. 
-
Victor

**Comment by thoeve** [comment]
These are PT errors and have nothing to do with PTN. Please ask for support on the official PT discord server.
