### ISSUE TITLE
[Change Request] Simplify bot selection for bot control in Discord

### ISSUE THREAD

**Issue by Ronanza** [ptnotifications/ptnotifications#45]
Hi,

when using commands like /today on Discord the bot for which the command/query is intendend needs to be selected. PTN will list the available bots as <instance #>-<bot name>. e.g /1-MyBTCbot
It would be cool if I could select the right bot by simply using the instance # instead of typing the entire name. e.g. /1
Now PTN will return an error that bot “/1” does not exist.

Thanks!

-Ronanza

**Comment by thoeve** [comment]
Fixed in [1.1.0](https://github.com/Roy4lz/ptnotifications/releases/tag/1.1.0)
