### ISSUE TITLE
2 ERROR BotService - Discord chat ID is invalid!

### ISSUE THREAD

**Issue by cnmars** [ptnotifications/ptnotifications#47]
#Enable or disable Discord notifications
discord_enabled = true/false
discord_bot_token = 
discord_channel_id =

this channel_id=  this server id or chnanel name???

**Comment by thoeve** [comment]
It's not the channel name it's the channel ID. 

![download](https://user-images.githubusercontent.com/36852659/40362691-9214acc4-5dcd-11e8-8fd5-48989b858261.png)

**Comment by cnmars** [comment]
已经解决 谢谢  be ok thanks
