### ISSUE TITLE
New version issue

### ISSUE THREAD

**Issue by FerHen1981** [ptnotifications/ptnotifications#48]
Hi,

I just upgraded to the latest version and doesn't seem to be able to read the data in http://localhost:XXXX although is working on the previous version with te same settings.

Could this be an error?

**Comment by thoeve** [comment]
Nothing in the code change that handles the connection with PT. So that's weird. Are you sure your PT is running and the api_token's match up?

**Comment by FerHen1981** [comment]
The new version:
#Set to the number of PT instance you are adding
profitTrailer_instances = 1

profitTrailer_address_1 = http://localhost:8096
profitTrailer_license_key_1 = xxxxxxxxxxxxxxxxxxxxxxxxxxx
#Make sure it matches the server.api_token variable in application.properties of your PT instance
profitTrailer_instance_api_token_1 = xxxx
And a copy paste of the PT settings
server.port = 8096
server.api_token = xxxx

**Comment by thoeve** [comment]
Can you try it without the space in your api tokens?

**Comment by FerHen1981** [comment]
Done that and now it's running! Great, thanks a lot!
