### ISSUE TITLE
WARN No appenders could be found for logger, Please initialize the log4j system properly

### ISSUE THREAD

**Issue by cnmars** [ptnotifications/ptnotifications#5]
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
5|PT-Notif | 2018-04-22 09:30 +08:00: log4j:WARN No appenders could be found for logger (nl.ptnotifications.app.a.a).
5|PT-Notif | 2018-04-22 09:30 +08:00: log4j:WARN Please initialize the log4j system properly.
5|PT-Notif | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
5|PT-Notif | 2018-04-22 09:32 +08:00: log4j:WARN No appenders could be found for logger (nl.ptnotifications.app.a.a).2018-04-22 09:32 +08:00: 
5|PT-Notif | 2018-04-22 09:32 +08:00: log4j:WARN Please initialize the log4j system properly.2018-04-22 09:32 +08:00: 
5|PT-Notif | 2018-04-22 09:32 +08:00: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.2018-04-22 09:32 +08:00:

**Comment by mattirie** [comment]
2018-04-21 21:37:51 INFO Main - Starting...
log4j:WARN No appenders could be found for logger (nl.ptnotifications.app.a.a).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

C:\Users\Administrator\Desktop\ptnotifications>pause
Press any key to continue . . .

**Comment by thoeve** [comment]
Could you explain how you start up PTN? Do you use PM2 or do you start it manually or using a .cmd file etc etc.

**Comment by cnmars** [comment]
Thank you very much for your reply. The program has been used normally
after I delete and redeploy. He is very good, very powerful, and I hope to
add more functions in the future and thank you again to bring such a good
program.

**Comment by mattirie** [comment]
2018-04-23 09:56:44 INFO Main - Starting...
log4j:WARN No appenders could be found for logger (nl.ptnotifications.app.a.a).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

C:\Users\Administrator\Desktop\ProfitTrailer-v2.0\ProfitTrailer\ptnotifications>pause
Press any key to continue . . .

I'm getting the same thing. I'm using this to start it...Start_windows.cmd
Is that not right?

**Comment by thoeve** [comment]
@mattirie Some others seem to have this issue and all managed to fix it as you can see above. Unfortunately I haven't figured out how they actually got it to work.

I did notice you put PTN in your profit trailer folder. Therefore I think they might be fighting over the certain folders or files which may cause this. Can you see if it works if you relocate your files in another folder that's not ProfitTrailer. Let me know how that works out please.

**Comment by mattirie** [comment]
2018-04-23 10:34:12 INFO Main - Starting...
log4j:WARN No appenders could be found for logger (nl.ptnotifications.app.a.a).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

C:\Users\Administrator\Desktop\ptnotifications>pause
Press any key to continue . . .

Same problem?

**Comment by cnmars** [comment]
我上次应该是因为文件解压不全导致不能正常工作的

2018-04-23 22:19 GMT+08:00 Roy4lz <notifications@github.com>:

**Comment by thoeve** [comment]
@mattirie Even though it's Chinese what he is saying he is saying that the reason it wasn't working for him because the files seem to got corrupted when unzipping. So perhaps redownloading and extracting might help.

**Comment by mattirie** [comment]
Still having the same problem. I've deleted it and reinstalled it several times to the VPS as well as my home computer. Nothing is working.

**Comment by Lentil-coco** [comment]
I have the same issue....

**Comment by thoeve** [comment]
What version of Java are you guys running?

**Comment by mattirie** [comment]
@Roy4lz  Java Product version 8.0.1710.11 
This is the only one it will let me download on the VPS.

**Comment by thoeve** [comment]
@mattirie Ok after a lot of debugging we finally figured out that this is error is caused when your telegram_channel_id is incorrect.

**Comment by mattirie** [comment]
I do not have telegram info filled out.  This is what it looks like in the settings. I only have the information filled out for discord. 

#Enable or disable Telegram notifications
telegram_enabled = false
telegram_bot_token = 
telegram_channel_id =

**Comment by thoeve** [comment]
@mattirie Any chance you can contact me on discord? Royal#4859

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
