### ISSUE TITLE
several commands on Discord not working or wrong string attached

### ISSUE THREAD

**Issue by cryptomail2018** [ptnotifications/ptnotifications#50]
"/version" not work 
"/update" not work 
"/all" gives a auto command of tableflip and is not excutable as a "/all" command

also cannot receive from github warning notification keeps coming up on CMD screen all the time in counts of 6

**Comment by cryptomail2018** [comment]
![capture](https://user-images.githubusercontent.com/35930742/41297195-d17405ec-6e88-11e8-9ae6-9bb7a4a82b3e.PNG)
this is what not seem to be right keep going forever

**Comment by thoeve** [comment]
/version not working is related to the fact it can't retrieve versions from GitHub. It's not really important. Just means that your api limit has been exceeded should fix it self sooner or later. /all can be fixed by simply adding a space after /all before pressing enter. /update should work fine.
