### ISSUE TITLE
Bot running although process is stopped

### ISSUE THREAD

**Issue by Ronanza** [ptnotifications/ptnotifications#54]
I’m running PTN v1.2.0 with 4 instances on the same machine. Since recently I’m receiving 2 “replys” when doing queries in Discord. e.g. /dca

**You have multiple instances running pick one:**
/1-bot1
/2-bot2
**/3-bot3
/4-bot4**

**You have multiple instances running pick one:**
/1-bot1
/2-bot2
**/3-bot4
/4-bot3**

Please note that the numbering of the last 2 bots is mixed up.
When I select /3 for example it will return both the DCA log of bot3 and bot4.

Also, when I close the application on the server it still answers queries!
In that case in the originally correct way:

**You have multiple instances running pick one:**
/1-bot1
/2-bot2
/3-bot3
/4-bot4

Where does the second PTC instance come from?
And more mysteriously, why is the Discord bot still answering queries if I close PTN on the server???

Thanks.

**Comment by thoeve** [comment]
Seems like you have another PTN java service running somewhere.

**Comment by Ronanza** [comment]
Nothing showed in the task manager. I restarted the server. This fixed the problem. Sorry for bothering...
