### ISSUE TITLE
Sell notification shows incorrect rate

### ISSUE THREAD

**Issue by timh77** [ptnotifications/ptnotifications#7]
This pair was recently sold by PT. PT shows a different sell rate compared to the Telegram message.

![telegram](https://user-images.githubusercontent.com/14058767/39094309-cbb59f0e-462d-11e8-8e9e-da787819f3f6.JPG)
![pt](https://user-images.githubusercontent.com/14058767/39094310-cc0f33f2-462d-11e8-80ed-8f82bd9080cd.JPG)

**Comment by thoeve** [comment]
Fixed in release [1.0.1](https://github.com/Roy4lz/ptnotifications/releases/tag/1.0.1)
