### ISSUE TITLE
Getting a sell and buy notification for the same pair

### ISSUE THREAD

**Issue by timh77** [ptnotifications/ptnotifications#8]
This pair was just sold but got two notifications, one for the sell and a second for a buy. The buy didn't happen.
Also the sell rate is invalid. The buy message shows the correct one.

![telegram](https://user-images.githubusercontent.com/14058767/39094327-12ad4ccc-462e-11e8-894e-57e52dafa89e.JPG)

**Comment by smoochy** [comment]
See https://github.com/Roy4lz/ptnotifications/issues/4

**Comment by thoeve** [comment]
Duplicate of #4
